name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: build-win
      run: |
        npm install pnpm
        pnpm install
        pnpm build
        pnpm go:build:win
        mv "jieshao.loract-umi-demo.exe" "loract-umi-demo_win_x64.exe"
    - name: Upload windows artifact
      uses: actions/github-action-publish-binaries@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          - args: 'loract-umi-demo_win_x64.exe'

